---
#
# Various strings and messages
#
strings:
  en: &en
    references:
      samm2:
        label: OWASP SAMM VERSION 2
        description: |-
          Software Assurance Maturity Model
          The Software Assurance Maturity Model (SAMM) is an open framework to help organizations formulate
          and implement a strategy for software security that is tailored
          to the specific risks facing the organization.
          https://owaspsamm.org/blog/2020/01/31/samm2-release/
      iso27001-2017:
        label: ISO 27001:2017
        description: |-
          ISO 27001:2017
      iso27001-2022:
        label: ISO 27001:2022
        description: |-
          ISO 27001:2022
    labels: ['Very Low', 'Low', 'Medium', 'High', 'Very High']
    KnowledgeLabels:
      [
        'Very Low (one discipline)',
        'Low (one discipline)',
        'Medium (two disciplines)',
        'High (two disciplines)',
        'Very High (three or more disciplines)',
      ]
    hardness: ['Very soft', 'Soft', 'Medium', 'High', 'Very high']
    maturity_levels:
      [
        'Level 0: Not present',
        'Level 1: Adoption of basic practices',
        'Level 2: High adoption of practices',
        'Level 3: Very high adoption of best practices',
        'Level 4: Advanced practices at scale',
      ]
# Default team
teams: ['Default']
